version: '3.9'

services:
    challenge:
        build:
            context: .
            target: ${NODE_ENV:-development}
        ports:
            - ${PORT:-3000}
        environment:
            DB_SYNCHRONIZE: ${DB_SYNCHRONIZE:-false}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
        depends_on:
            - postgres
        networks:
            - challenge_network

    postgres:
        image: postgres:17
        restart: always
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - 5432:${DB_PORT}
        environment:
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
        networks:
            - challenge_network

volumes:
    db:
        driver: local

networks:
    challenge_network:
        name: challenge_network
        driver: bridge
