name: Challenge Deployment

on:
    pull_request:
        branches: [development, staging, testing, main, master]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        timeout-minutes: 20

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        env:
            DB_HOST: localhost
            DB_PORT: 5432
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASS: ${{ secrets.DB_PASS }}

        services:
            postgres:
                image: postgres:17
                env:
                    POSTGRES_PASSWORD: ${{ secrets.DB_PASS }}
                    POSTGRES_DB: ${{ secrets.DB_NAME }}
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Run Lint and Prettier
              run: npm run lint

            - name: Run Tests
              run: npm run test
              env:
                  NODE_ENV: test
                  HOST: http://localhost
                  PORT: 3000
                  DB_USER: ${{ secrets.DB_USER }}
                  DB_PASS: ${{ secrets.DB_PASS }}
                  DB_HOST: localhost
                  DB_PORT: 5432
                  DB_NAME: ${{ secrets.DB_NAME }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
